---
rpi:
  hosts:
    192.168.1.0:

  vars:
    ansible_ssh_user: pi
    ansible_ssh_pass: raspberry
    server_name: pihole
    ssl_pem: pihole.pem
    timezone: America/Toronto
    pihole_dns: 208.67.222.222;208.67.220.220
